language: php

php:
  - 8.2
  - 8.3

matrix:
  allow_failures:
    - php: 8.0

install:
  - composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache

# Optional: define environment settings
env:
  global:
    - COMPOSER_FLAGS="--prefer-dist --no-interaction"

# Optional: run checks like linting or static analysis
# before_script:
#   - composer lint
#   - composer analyse

# Optional: use GitHub Actions as Travis CI is deprecated by many projects
# Consider migrating if future support is needed
